### ISSUE TITLE
create-pkg.sh missing fakeroot dependent

### ISSUE THREAD

**Issue by suntong** [mh-cbon/go-github-release#11]
From [my latest build log](https://api.travis-ci.org/jobs/229484319/log.txt?deansi=true), it seems that the `fakeroot` command should have been added to the `create-pkg.sh`'s dependent packages:

```
mkdirAll /tmp/go-bin-deb201915466/386
+ go-bin-deb generate -a 386 --version 0.1.0 -w /tmp/go-bin-deb201915466/386 -o /home/travis/gopath/src/github.com/go-cc/cc2py/cc2py-386.deb
exec: "fakeroot": executable file not found in $PATH
panic: exit status 1

```

**Comment by mh-cbon** [comment]
faced that problem yesterday, fixed now.
