### ISSUE TITLE
.exe for windows

### ISSUE THREAD

**Issue by suntong** [mh-cbon/go-github-release#12]
Since >99% Go code will be compiled into a single executable file, and run on command line, please provide a more simpler option to build windows executables -- just a plain .exe file available within the release folder, without any packaging. 

All the user need to do is to download the official .exe file, and put into their PATH, or C:\WINDOWS if they don't know what PATH is. 

Please consider. Thx.

**Comment by mh-cbon** [comment]
for reference you can check that bump script,
https://github.com/mh-cbon/changelog/blob/master/.version.sh

+/- it does what you want 
https://github.com/mh-cbon/changelog/releases/tag/0.0.27

**Comment by suntong** [comment]
Sorry but I've read the two links/files, and come back double-checked several times, but am still unable to figure out what you are trying to say. Please elaborate more.

**Comment by mh-cbon** [comment]
There it builds the bin files,

```
666 rm-glob -r build/
666 rm-glob -r assets/
666 build-them-all build main.go -o "build/&os-&arch/&pkg" --ldflags "-X main.VERSION=!newversion!"
```

Here it creates archives, a new release on gh, then upload assets

```
  philea -s -S -p "build/windows*/*" "666 archive create -f -o=assets/%dname.zip -C=build/%dname/ ."
  philea -s -S -e windows*/** -p "build/*/**" "666 archive create -f -o=assets/%dname.tar.gz -C=build/%dname/ ."
  666 gh-api-cli create-release -n release -o mh-cbon -r changelog \
    --ver !newversion! -c "changelog ghrelease --version !newversion!" \
    --draft !isprerelease!
666 gh-api-cli upload-release-asset -n release --glob "assets/*" -o mh-cbon -r changelog --ver !newversion!
```

currently you want to check
https://github.com/mh-cbon/gh-api-cli#gh-api-cli-upload-release-asset--help
https://github.com/mh-cbon/build-them-all#build

**Comment by suntong** [comment]
Thanks. Please put above in the README of https://github.com/mh-cbon/go-github-release, as an alternative to `wix`, when you have some time. 

Further questions, 

> philea -s -S -p "build/windows*/*" "666 archive create -f -o=assets/%dname.zip -C=build/%dname/ ."

If I want to release just plain .exe files instead of zipping them up, copying them from `build/windows*/*` as `assets/windows*/*` would be good enough, right? 

> philea -s -S -e windows*/** -p "build/*/**" "666 archive create -f -o=assets/%dname.tar.gz -C=build/%dname/ ."

GH is already creating the source .tar.gz file for each release. Why this step necessary? 

Moreover, the `archive` in the above two commands, which both contains `666 archive`, what is it? 

What does the notation of `!newversion!` or `!isprerelease!` mean? Should I use them literally? 

Is any of you tool being release like above? Is the commands for that specific tool available somewhere? Or better yet, do you have a log of releasing any of you tool as above (or for windows at least)? 

Thanks

**Comment by mh-cbon** [comment]
Its not an alternative to wix, they have different features.

Those commands are to be updated appropriately indeed, they are just examples.

> GH is already creating the source .tar.gz file for each release. Why this step necessary?

GH is zipping the source, in above example it zip the build.

> Moreover, the archive in the above two commands, which both contains 666 archive, what is it?

https://github.com/mh-cbon/666 is a program to show success/failure status, 
https://github.com/mh-cbon/archive is only a go bin to create zip/tar for any platforms.

> What does the notation of !newversion! or !isprerelease! mean? Should I use them literally?

Its a bump script, a script you run when you go from version A to version B.
Those values are valid only within this file (https://github.com/mh-cbon/gump)
They are used currently to put your assets on the right release version.
But you might replace it with static values i guess, give it a try.

> Is any of you tool being release like above? 

Would not have shown to you otherwise

> Is the commands for that specific tool available somewhere? 

on my gh.

> Or better yet, do you have a log of releasing any of you tool as above?

yep, my gh account, everything public is there.

**Comment by suntong** [comment]
>> Is the commands for that specific tool available somewhere?

> on my gh.

>> Or better yet, do you have a log of releasing any of you tool as above?

> yep, my gh account, everything public is there.

Sorry can you give one specific url please, I've been looking at many of your repos, but still unable to find any. Thanks a lot for your help.

**Comment by mh-cbon** [comment]
sorry, what are you looking for ?

**Comment by suntong** [comment]
I am looking for any of you tool that is released in .exe format for windows, using the build steps as you prescribed above (preferable with one specific url that contains all the building logs, but that's optional). Thanks.

**Comment by mh-cbon** [comment]
ah ok, thanks, indeed there is no such thing as is. you ll need to do it by yourself with the leads i left you.

**Comment by mh-cbon** [comment]
should be something like 

```
build-them-all build *.go -o "build/&pkg-&os-&arch"
gh-api-cli create-release -n xxx --guess --ver xxx
gh-api-cli upload-release-asset -n xxx --glob "build/*" --guess  --ver xxxx
```

**Comment by suntong** [comment]
Thanks, we can close this once the above are in the README of https://github.com/mh-cbon/go-github-release

**Comment by suntong** [comment]
Hi @mh-cbon, Would you like to contribute into https://github.com/goreleaser/goreleaser instead, please? (so that instead of fixing this, you can focus on https://github.com/goreleaser/goreleaser/issues/242) 
I'm sad to see talented people working on their own islands instead of collaborating with the more popular ones. 
Thanks

**Comment by mh-cbon** [comment]
unlikely to happen, unfortunate. Their philosophy is too far from mine, in the end, i m happy the end user can choose what is best for him.

> ..working on their own islands..

true in some ways, but that s diversity, right ?

That being said they have snapcraft and dmg files support, i m jealous.

___________________________

(did he just jerk online because of his stars ? https://github.com/goreleaser/goreleaser/commit/32fa52e465c715729e28f6bebeea596082ec17ef#diff-04c6e90faac2675aa89e2176d2eec7d8 to be friendly honest, i don't drink that)

**Comment by suntong** [comment]
:smiley: :smiley:

**Comment by mh-cbon** [comment]
https://github.com/mh-cbon/go-github-release#github-release-page
