### ISSUE TITLE
Doesn't AppVeyor already have suitable Wix?

### ISSUE THREAD

**Issue by solvingj** [mh-cbon/go-github-release#14]
https://www.appveyor.com/docs/build-environment/

Wix is listed, 3.11+.  Looks like you might be doing a few redundant steps.  Maybe there's a reason though.

**Comment by mh-cbon** [comment]
true! fixed, thanks. For future readers find manual wix setup here https://github.com/mh-cbon/go-msi/blob/master/testing/vagrant-setup.sh#L48
