### ISSUE TITLE
Multiple .travis*.yml files - What is the Interaction?

### ISSUE THREAD

**Issue by solvingj** [mh-cbon/go-github-release#17]
In this repo, there are three .travis*.yml files. 

- .travis.yml
- .travis-repo.yml
- .travis-rpm.yml

Not being an expert on Travis, it's not clear if all three of these are intended to be used together in this Repo as-is, and that Travis CI has special handling for multiple .travis*.yml files, or if they are simply provided as references for the tutorial.  I did look through some Travis documentation and do some google searching but could not find a clear reference explaining if/how this works.  I found lots of discussion about it, but nothing I could comprehend. 

Can you please clarify what's happening there?

**Comment by mh-cbon** [comment]
Those are just demo files, travis accepts only one file. feel free to ask when you have a question.

**Comment by solvingj** [comment]
Is it possible to build both DEB and RPM in the same travis file?

**Comment by mh-cbon** [comment]
long story short, yes, https://github.com/mh-cbon/emd/blob/master/.travis.yml#L43
