### ISSUE TITLE
Bintray Examples

### ISSUE THREAD

**Issue by solvingj** [mh-cbon/go-github-release#21]
I've posted your projects to Bintray, currently just as .MSI and Chocolatey packages (Nuget). 

- https://bintray.com/bincrafters/public-choco
- https://bintray.com/bincrafters/public-msi

Here are some notes about the nuances in no particular order:
- Nuget packages posted to bintray can be accessed via chocolatey: see `choco source add`
- This is nice for using choco but bypassing the public repository moderation, also for testing in preparation for pushing to chocolatey central
- The same basic advantage exist for both .deb and .rpm packages on linux
- Will add linux next
- I've only added the x86 pipeline for nuget/chocolatey because Nuget's package structure makes it harder than it's worth to package both x64 and x86 via appveyor.  
- I did add the MSI files for both architectures, because it's easy with MSI
- I've used jfrog's CLI, which has pro's and cons.  I like because I can test my upload commands locally. It's also written in Go co-incidentally.
- You have to create the packages on appveyor manually before appveyor will upload
- "--override" on jfrog cli doesn't work for nuget packages. It's an API problem, ticket open. 
- I made appveyor as simple as possible for demo.  Please add back the tag-version mapping and all the other logic that was lost if desired. (For example, you can refactor to do x64 nuget packages if you want). 
- We can now express dependencies between packages, for example I think emd effectively depends on changelog
-

**Comment by mh-cbon** [comment]
cool stuff! are there any files i can look into for the scripting ?

**Comment by solvingj** [comment]
Yes, I forked each repo, look there.

**Comment by solvingj** [comment]
Ok, everything is fully implemented now: (in forks under the bincrafters organization).

# gump, emd, changelog 
Each of these projects now features:  
- a working travis recipe which features: 
-- Matrix builds for amd64 and i386
-- Builds both .rpm and .deb and pushes each to corresponding bintray repos
-- Uses apt-get to pull go-bin-deb from bintray for packaging debs
-- Uses very simple custom docker image which has go-bin-rpm for packaging rpms
- a working appveyor recipe which features:
-- Matrix builds for x64 and x86... but x64 is disabled for reasons to be discussed later
-- Uses chocolatey to pull go-msi from chocolatey for packaging MSI's and NUPKGs
-- Builds both .msi and .nupkg and pushes each to corresponding bintray repos
-- Note: For .msi files, Bintray has "Generic Repo" type
- Uses JFrog CLI for uploading to bintray rather than appveyor/travis providers
-- bt_user and bt_key env variables are added in appveyor/travis web UI rather than config

# go-msi, go-bin-rpm, go-bin-deb
Each has all the same things as the other above with the following differences:
- go-msi
-- Has no travis recipe, only appveyor
- go-bin-deb
-- Has no appveyor recipe, only travis
-- skips the go-bin-rpm related steps, has no rpm.json
- go-bin-rpm
-- Has no appveyor recipe, only travis
-- skips the go-bin-deb related steps, has no deb.json

Nuances you might hit trying to port these recipes:
- x86 debian packages have to be created with arch "i386" for apt-get install to associate properly
- Nuget wants both x64 and x86 files in one package, which is incompatible with appveyor matrix
-- One workaround is to bypass the matrix, and build both together (which is how you had it before)
-- Another is to just build the x86 for windows, which is fine for your tools (IMO)
-- You have to pre-create the package on Bintray before uploading which is annoying
-- You can script it with the jfrog cli "pc" option on your local machine

You can automatically reference the existing packages in the corresponding package managers after adding the respective bintray repository to your local list as follows: 

- Debian
-- `echo "deb https://dl.bintray.com/bincrafters/public-deb unstable main" | sudo tee -a /etc/apt/sources.list`

- Redhat/Centos/Fedora
-- `wget https://bintray.com/bincrafters/public-rpm/rpm -O bintray-bincrafters-public-rpm.repo && sudo mv bintray-bincrafters-public-rpm.repo /etc/yum.repos.d/`

- Windows
-- `choco source add -n=bincrafters -s="https://api.bintray.com/nuget/bincrafters/public-choco"`

**Comment by solvingj** [comment]
Another nuance I forgot to mention, there is a step in the travis recipes: 

``` 
  - cd $HOME/gopath/src/github.com
  - mv $BT_SUBJECT $ORIGINAL_AUTHOR
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/$ORIGINAL_AUTHOR/$APP
```
This is necessary because of a nuance in the go dependency resolution system when working with a forked repository.  You won't need this outside of a fork. 

On Appveyor, we get to workaround the same thing using this one variable: 
`clone_folder: c:\gopath\src\github.com\mh-cbon\emd`

**Comment by solvingj** [comment]
There seems to be an issue with the `emd` package on windows. 

`Command ["C:\WINDOWS\System32\msiexec.exe" /i "C:\ProgramData\chocolatey\lib\emd\tools\emd-386-0.0.12.msi" /quiet ] exited with '1603'.`

No time to debug at the moment.

**Comment by solvingj** [comment]
Because this repo is named `go-github-release` maybe the tutorials should be left as-is, and the bintray examples should be documented in a new repo named `go-bintray-release` or something.

**Comment by mh-cbon** [comment]
hi @solvingj 

about the msi error you got, please check, 
https://support.microsoft.com/en-us/help/834484/you-receive-an-error-1603-a-fatal-error-occurred-during-installation-e
https://www.msigeek.com/715/how-to-troubleshoot-the-error-1603-fatal-error-during-installation

I did the check on my windows2k12 vagrant, it worked
```sh
[mh-cbon@pc2 testing] $ vagrant winrm -c "msiexec.exe /i C:\\vagrant\\emd-386.msi /quiet"
[mh-cbon@pc2 testing] $ vagrant winrm -c "msiexec.exe /i C:\\vagrant\\emd-386.msi /quiet"
[mh-cbon@pc2 testing] $ vagrant winrm -c "msiexec.exe /x C:\\vagrant\\emd-386.msi /quiet"
[mh-cbon@pc2 testing] $ vagrant winrm -c "msiexec.exe /i C:\\vagrant\\emd-386.msi /quiet"
[mh-cbon@pc2 testing] $ vagrant winrm -c "msiexec.exe /x C:\\vagrant\\emd-386.msi /quiet"
[mh-cbon@pc2 testing] $ vagrant winrm -c "msiexec.exe /i C:\\vagrant\\emd-amd64.msi /quiet"
[mh-cbon@pc2 testing] $ vagrant winrm -c "msiexec.exe /x C:\\vagrant\\emd-amd64.msi /quiet"

PS C:\Users\vagrant> emd
emd - 1.0.0
```

Please, Keep me up to date if the problem persists.

> Because this repo is named go-github-release maybe the tutorials should be left as-is, and the bintray examples should be documented in a new repo named go-bintray-release or something.

That will be very small guide, no ?

Besides, as many had ask about that, as using gh-pages makes big repositories, and its clunky anyway, i will move to bintray for this guide, and myself.

______________

Thanks to your implementation, I have been able to implement the bintray/travis thing (so painful) for go-bin-deb, with some very minor adjustments. All i got to do now is 
- apply it on relevant repos, 
- test all the things, 
- figure out how to put that down in the guide

https://github.com/mh-cbon/go-bin-deb/blob/master/.travis.yml

for backward compatibility reasons many existing will be kept, but not updated anymore unless some fix.

**Comment by solvingj** [comment]
All sounds good... this is a nice one!
```
  - (yes n | ./jfrog bt pc --key=$BTKEY --user=$GH_USER --licenses=MIT --vcs-url=https://github.com/$GH_USER/$GH_APP $GH_USER/$GH_APP/$GH_APP) || echo "package already exists"
```

**Comment by mh-cbon** [comment]
about that see also https://github.com/JFrogDev/jfrog-cli-go/issues/88 (i did not tried it so far)

**Comment by mh-cbon** [comment]
> go-msi
> -- Has no travis recipe, only appveyor

Its better to keep the linux build of go-msi, so the user can access commands like `check-json` / `set-guid` / `to-rtf` independently of their underlying os.

**Comment by mh-cbon** [comment]
>  -- You can script it with the jfrog cli "pc" option on your local machine

with https://github.com/JFrogDev/jfrog-cli-go/issues/90 it can be into the build script, but if another good solution exists, worth to mention.

**Comment by mh-cbon** [comment]
> Nuget wants both x64 and x86 files in one package, which is incompatible with appveyor matrix
> -- One workaround is to bypass the matrix, and build both together (which is how you had it before)
> -- Another is to just build the x86 for windows, which is fine for your tools (IMO)

yes, go msi needs updates.

https://github.com/chocolatey/choco/wiki/HelpersInstallChocolateyInstallPackage#-file64-string
https://github.com/mh-cbon/go-msi/blob/master/templates/choco/chocolateyInstall.ps1#L5
https://github.com/mh-cbon/go-msi/blob/master/templates/choco/pkg.nuspec#L34

but uninstall helper command does not have the -File64 arg.
https://chocolatey.org/docs/helpers-uninstall-chocolatey-package

For the moment i will keep using only one file, 386 one.

**Comment by solvingj** [comment]
Depending on how much time you're interested in investing in adding features to Go-msi, Choco packages have the option of not even containing the MSI.  Instead, they can be built with URL's pointing to the MSI files, which can then be intelligently chosen and downloaded based on architecture at install time.  Many choco recipe's for third party packages are written this way to get around licensing issues for redistributing.   So, from a CI point of view, you might have the 32 and 64 bit runs of appveyor just create the MSI's and put them on bintray "generic" repository.  Then, you can create a choco package for both whenever you want because you can predict the URL's based on the variables.  You can do this either in the 32 bit run, or the 64 bit run, or be lazy and just let it happen in both.  You might also just put a third "arch" in the matrix called choco, and for that architecture, just create the choco package.   All kinda hacky.  It's nugets fault.

**Comment by solvingj** [comment]
Oh, and I also almost mentioned the package creation in the CI recipe in my original post, but because it's annoying how it fails and such, I chose not to. Sorry to see that you ultimately worked your way through all the related problems with that the hard way :(  I should have explained.

**Comment by mh-cbon** [comment]
> Depending on how much time you're interested in investing in adding features to Go-msi, Choco packages have the option of not even containing the MSI. Instead, they can be built with URL's pointing to the MSI files, which can then be intelligently chosen and downloaded based on architecture at install time. Many choco recipe's for third party packages are written this way to get around licensing issues for redistributing. So, from a CI point of view, you might have the 32 and 64 bit runs of appveyor just create the MSI's and put them on bintray "generic" repository. Then, you can create a choco package for both whenever you want because you can predict the URL's based on the variables. You can do this either in the 32 bit run, or the 64 bit run, or be lazy and just let it happen in both. You might also just put a third "arch" in the matrix called choco, and for that architecture, just create the choco package. All kinda hacky. It's nugets fault.

have example on hand ?

> Oh, and I also almost mentioned the package creation in the CI recipe in my original post, but because it's annoying how it fails and such, I chose not to. Sorry to see that you ultimately worked your way through all the related problems with that the hard way :( I should have explained.

this https://github.com/mh-cbon/go-msi/blob/master/appveyor.yml#L59 ?

**Comment by solvingj** [comment]
Here's a decent example i think: 
https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/curl

**Comment by mh-cbon** [comment]
thanks! 

looks likes it s  a bunch of ps script.
i think it happens at https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/curl/update.ps1#L32
https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/curl/tools/chocolateyInstall.ps1#L4

i might try to put an SO question with a reward, honestly ps is not that much of my taste.

**Comment by mh-cbon** [comment]
the golang implementation part is really easy from here.

**Comment by solvingj** [comment]
The choco team has quite a few people in the gitter and they do answer questions:

https://gitter.im/chocolatey/choco

Someone in the room might even help with the PS.

**Comment by mh-cbon** [comment]
chat: bad idea.

**Comment by mh-cbon** [comment]
I found a pretty nasty bug in travis, it does not honor GOARCH in

```yml
env:
  matrix:
    - GOARCH=amd64 OSARCH=amd64
```

instead i have to use any another name.
```yml
    - OKARCH=amd64 OSARCH=amd64
```

https://github.com/travis-ci/travis-ci/issues/8313

**Comment by solvingj** [comment]
I was so confused by this, spent so much time !!! :(  thank you for sharing the bug report.

**Comment by mh-cbon** [comment]
yeah, there s also this kind of problems, sometimes, https://github.com/appveyor/ci/issues/1752

**Comment by mh-cbon** [comment]
at some points things should get back to normal,

https://github.com/appveyor/ci/issues/1755
https://github.com/appveyor/ci/issues/1754
https://github.com/mh-cbon/go-msi/blob/master/appveyor.yml#L70

**Comment by mh-cbon** [comment]
all up to date.
