### ISSUE TITLE
Updating GH releases from both appveyor and travis

### ISSUE THREAD

**Issue by mattstratton** [mh-cbon/go-github-release#23]
First of all, thank you for this great workflow! I already had something working with goreleaser to handle brew and my linux/mac stuff into GH Releases via travis. But I super needed a solution for msi.

What I'm trying to figure out is how to have two different tools update the same release - appveyor is claiming that it uploads the artifacts to GH for the release, but the only artifacts that are added to the actual release are the ones that came from Travis (which was the first one to complete).

Have you been able to successfully push, say, rpm's from travis and msi from appveyor to the same GH release tag?

**Comment by mh-cbon** [comment]
> Have you been able to successfully push, say, rpm's from travis and msi from appveyor to the same GH release tag?

yes, see https://ci.appveyor.com/project/mh-cbon/gump/build/10#L408, https://github.com/mh-cbon/gump/releases/tag/0.1.9, https://travis-ci.org/mh-cbon/gump

> ...figure out is how to have two different tools update the same release ...

that does not matter. They will create the release if it does not exist.
If the file target exists, you might need to explicitly set an overwrite flag to true. Those are options specific to the ci provider.

If you stumble upon a situation where the upload via travis/appveyor provided modules is not suitable, you might simply use a command such as `gh-api-cli upload-release-asset -t %GH_TOKEN% -g "*-386.msi" -o %GH_USER% -r %GH_APP% --ver %VERSION%` to get the same result.

hth

**Comment by mattstratton** [comment]
I honestly am not sure what problem I was having with appveyor - mostly that the syntax of the release provider is slightly different than travis, which I am used to. But I got it working. 

Thanks for these tools and these workflows!

**Comment by mh-cbon** [comment]
that s ok, ci files looks easy but they are not.

you are welcome
