### ISSUE TITLE
produce debian repository over gh-pages

### ISSUE THREAD

**Issue by suntong** [mh-cbon/go-github-release#5]
> produce debian repository over gh-pages

Yeah!! Now we're talking, :-)

Opening a page to get notified when it is done. :-)

**Comment by mh-cbon** [comment]
https://github.com/mh-cbon/go-bin-deb/blob/master/setup-repository.sh

**Comment by suntong** [comment]
I think [L114-L117](https://github.com/mh-cbon/go-bin-deb/blob/master/setup-repository.sh#L114-L117) are better move to https://github.com/mh-cbon/go-bin-deb/blob/master/setup-repository.sh#L106, right?

**Comment by suntong** [comment]
The `setup-repository.sh` is supposed to be used in the travis file. Is there a how-to anywhere?

Else can you reopen this issue and close it after the hwo-to is published pls?

**Comment by mh-cbon** [comment]
its here https://github.com/mh-cbon/go-github-release#rpm--debian

i understand the howto deserve refactoring to be more readable.

**Comment by suntong** [comment]
Yes, please. 

I kind of followed along, and was able to 

- [get my build successful](https://travis-ci.org/suntong/cascadia/builds/222488671). 
- and I [get my debian package built & uploaded successful](https://github.com/suntong/cascadia/releases/tag/1.1.0) as well. 

However, I don't see my debian repository in gh-pages, which I presume to be http://suntong.github.io/ppa/.  I checked my https://github.com/suntong/ppa, and it is still empty. 

**UPDATE:** Forgot to allow my newly created repo in travis, maybe that's why, but still, 

Could you look into it and see what I'm missing please? 

Thanks a lot!

**Comment by mh-cbon** [comment]
Hi,

See at https://travis-ci.org/suntong/ppa/builds/222488671 at bottom it says something like

/home/travis/.travis/job_stages: line 53: $'\302\240-': command not found

I guess because in,
https://github.com/suntong/cascadia/blob/master/.travis.yml

There should be A GH variable like 
https://github.com/mh-cbon/emd/blob/master/.travis.yml#L12

The variables are messy needs fix in doc / scripts.

Also,
 I don t think you ll be able to only drop the cmd here, and trick the GH var like this
https://github.com/suntong/cascadia/blob/master/.travis.yml#L39

I m afraid tokens / variables does not match.

Those scripts definitely needs updates. They have been working for me so far, but for new people it might need clearer error messages ect.

**Comment by mh-cbon** [comment]
so far it been made so one repo &lt;&gt; one app

**Comment by mh-cbon** [comment]
Also i see the change.log is empty, weird, as the 1.1.0 has changes (https://github.com/suntong/cascadia/releases)
https://github.com/suntong/cascadia/blob/master/change.log

**Comment by mh-cbon** [comment]
just in case you missed in, yu might want to use the template to show the snipper to install cascadia via go / deb

like 
https://github.com/mh-cbon/emd#linux-rpmdeb-repository
https://github.com/mh-cbon/emd#go

did you miss it ? Dont know.

**Comment by suntong** [comment]
> /home/travis/.travis/job_stages: line 53: $'\302\240-': command not found

I figured it out and get it working -- I was copying the whole thing from the web, however, the web nowadays is not the best place to copy commands from. I.e., spaces will turn into "`\302\240`". I fixed that and the `setup-repository` was started. 

> I don t think you ll be able to only drop the cmd here, and trick the GH var like this
https://github.com/suntong/cascadia/blob/master/.travis.yml#L39

Yeah it works fine:

```
+[suntong/ppa == ]
sh: 19: [suntong/ppa: not found
+echo suntong/ppa+
cut -d / -f 2
+REPO=ppa
+echo suntong/ppa
+cut -d / -f 1
+USER=suntong
```

> Also i see the change.log is empty

Oh, yeah, I was waiting for #6 to download all your tools, so I simulated every step _manually_. I put in empty log there just in case the tool need it. 

> just in case you missed in, yu might want to use the template to show the snipper to install cascadia via go / deb

Yeah, sure. I'm just not there yet. :-)

> so far it been made so one repo <> one app

The "`<>`" doesn't read as "_not equal_" but "_correspond_", right? 
Hope eventually we can get it working. 

Looking at the [build log](https://api.travis-ci.org/jobs/222556070/log.txt?deansi=true), I think there are a few things you can note in your how to:

- First, use variables as much as possible, e.g., 

```
after_deploy:
  - curl -L https://raw.githubusercontent.com/mh-cbon/go-bin-deb/master/setup-repository.sh | GH=$USER_NAME/$USER_REPO EMAIL=$USER_EMAIL sh -xe
```

- allow the repo `ppa` in travis if it is newly created
- create gh-pages ahead of the time, otherwise, will get:

```
+git checkout gh-pages
+error: pathspec 'gh-pages' did not match any file(s) known to git.

```

- Do not reuse tags if the app has changed. Otherwise, will get:

```
Current tag is: 1.1.0

Deploying application
cascadia-386.deb already exists, skipping.
cascadia-amd64.deb already exists, skipping.
```

- However, if central single `ppa` repo is used, how to deal with the case of package having multiple versions? 

- And maybe some other things in the [build log](https://api.travis-ci.org/jobs/222556070/log.txt?deansi=true) that I've missed.

**Comment by suntong** [comment]
The latest build,
https://travis-ci.org/suntong/cascadia/builds/222615423

errors at the bottom, on line 2362:

```
Local repo [ppa] successfully added.
You can run 'aptly repo add ppa ...' to add packages to repository.
+/home/travis/gopath/src/github.com/suntong/cascadia/D/aptly_0.9.7_linux_amd64/aptly repo add -config=/home/travis/gopath/src/github.com/suntong/cascadia/D//aptly.conf ppa ../pkg
Loading packages...
[!] Unable to process ../pkg: stat ../pkg: no such file or directory
[!] Some files were skipped due to errors:
  ../pkg
ERROR: some files failed to be added

```

**Comment by mh-cbon** [comment]
> Do not reuse tags if the app has changed

in that case, i prefer to re publish until it just works. One might want to re publish, as you noticed it has some implications to be handled.
The question is worthy because my practice which I consider the good one, is not shared by everyone, for example chocolaty team does not like this at all.


> However, if central single ppa repo is used, how to deal with the case of package having multiple versions?

I d say, the ppa should contain all version, the distro package manager client will handle the versioning.
to be confirmed in practice.

**Comment by mh-cbon** [comment]
#21 #18
